/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocRouteImport } from './routes/troc'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as ForumIdRouteImport } from './routes/forum.$id'
import { Route as CommunityIdRouteImport } from './routes/community.$id'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'

const TrocRoute = TrocRouteImport.update({
  id: '/troc',
  path: '/troc',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListingsRoute,
} as any)
const ForumIdRoute = ForumIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ForumRoute,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunityRoute,
} as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRouteWithChildren
  '/forum': typeof ForumRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/pets': typeof PetsRoute
  '/troc': typeof TrocRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/community/$id': typeof CommunityIdRoute
  '/forum/$id': typeof ForumIdRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRouteWithChildren
  '/forum': typeof ForumRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/pets': typeof PetsRoute
  '/troc': typeof TrocRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/community/$id': typeof CommunityIdRoute
  '/forum/$id': typeof ForumIdRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRouteWithChildren
  '/forum': typeof ForumRouteWithChildren
  '/listings': typeof ListingsRouteWithChildren
  '/pets': typeof PetsRoute
  '/troc': typeof TrocRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRoute
  '/community/$id': typeof CommunityIdRoute
  '/forum/$id': typeof ForumIdRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/community'
    | '/forum'
    | '/listings'
    | '/pets'
    | '/troc'
    | '/goals'
    | '/history'
    | '/recipes'
    | '/community/$id'
    | '/forum/$id'
    | '/listings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/community'
    | '/forum'
    | '/listings'
    | '/pets'
    | '/troc'
    | '/goals'
    | '/history'
    | '/recipes'
    | '/community/$id'
    | '/forum/$id'
    | '/listings/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chat'
    | '/community'
    | '/forum'
    | '/listings'
    | '/pets'
    | '/troc'
    | '/_authenticated/goals'
    | '/_authenticated/history'
    | '/_authenticated/recipes'
    | '/community/$id'
    | '/forum/$id'
    | '/listings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  ForumRoute: typeof ForumRouteWithChildren
  ListingsRoute: typeof ListingsRouteWithChildren
  PetsRoute: typeof PetsRoute
  TrocRoute: typeof TrocRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/troc': {
      id: '/troc'
      path: '/troc'
      fullPath: '/troc'
      preLoaderRoute: typeof TrocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/forum/$id': {
      id: '/forum/$id'
      path: '/$id'
      fullPath: '/forum/$id'
      preLoaderRoute: typeof ForumIdRouteImport
      parentRoute: typeof ForumRoute
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CommunityRouteChildren {
  CommunityIdRoute: typeof CommunityIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityIdRoute: CommunityIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface ForumRouteChildren {
  ForumIdRoute: typeof ForumIdRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumIdRoute: ForumIdRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

interface ListingsRouteChildren {
  ListingsIdRoute: typeof ListingsIdRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsIdRoute: ListingsIdRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CommunityRoute: CommunityRouteWithChildren,
  ForumRoute: ForumRouteWithChildren,
  ListingsRoute: ListingsRouteWithChildren,
  PetsRoute: PetsRoute,
  TrocRoute: TrocRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
